---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "csi-ceph-hdd-ms1"
